// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Basic plugin for manipulating important parameters.","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"MadeWithMv","status":true,"description":"Show a Splash Screen \"Made with MV\" and/or a Custom Splash Screen before going to main screen.","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"OrangeMapshot","status":true,"description":"This plugin will save a picture of the entire map on a Mapshots folder when you press a key. <OrangeMapshot>","parameters":{"useMapName":"true","layerType":"0","drawAutoShadows":"true","drawEvents":"true","keyCode":"81","imageType":"png","imageQuality":"100","imagePath":"./Mapshots"}},
{"name":"OrangeOverlay","status":true,"description":"v1.1.4 - Adds overlay images to the map <OrangeOverlay>","parameters":{"Organized Folders":"false","Parallax Layer Filename":"par","Ground Layer Filename":"ground","Light Layer Filename":"light","Shadow Layer Filename":"shadow","Light Opacity":"185","Quick Start":"true","Bush Region ID":"7","Fog Switch ID":"1","Light Switch ID":"2","Parallax Switch ID":"3","Shadow Switch ID":"4"}},
{"name":"YEP_RegionRestrictions","status":true,"description":"v1.04 Use regions to block out Events and/or the player from\nbeing able to venture into those spots.","parameters":{"Player Restrict":"0","Event Restrict":"0","All Restrict":"2","Player Allow":"0","Event Allow":"0","All Allow":"1"}},
{"name":"OrangeLighting","status":true,"description":"Lighting system <OrangeLighting>","parameters":{"lightMaskSwitch":"1","opacityVariable":"1","tintSpeed":"0.3","defaultMaskColor":"black"}},
{"name":"OrangeLightingEventLight","status":true,"description":"Event Lights <OrangeLightingEventLight>","parameters":{"eventRadius":"40","eventColor":"#FFFFFF","eventFlicker":"false"}},
{"name":"OrangeLightingPlayerLight","status":true,"description":"Player Lights <OrangeLightingPlayerLight>","parameters":{"playerRadius":"40","playerColor":"#FFFFFF","playerFlicker":"false","flashlightSwitch":"0"}},
{"name":"SilvSkipTitle","status":true,"description":"v1.00 Skips Title Screen\r\n<SilverSkipTitle>","parameters":{"Skip Title Screen Entirely":"true","Skip If Savefile Present":"true","FadeOut Title":"false"}}
];
